CREATE TABLE member(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    account VARCHAR(50) NOT NULL,
    mail VARCHAR(50) NOT NULL,
    password VARCHAR(128) NOT NULL,
    random_flag TINYINT(1) NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;


